matrix:
  include:
  - language: java
    jdk: openjdk13
    install: travis_wait 30 mvn install
    script:
      - cd Server/online.quar/
      # run unit test here
      - mvn spring-boot:run
    # java jobs here
  - language: c
    before_install:
      - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
    install:
      - arduino --install-library "ESP32 AnalogWrite"
      - arduino --install-library "ServoESP32"
      - arduino --install-library "Smartcar shield"
    script:
      - build_platform esp32
os:
 - linux
dist: bionic
addons:
  apt:
    sources:
#      - ppa:chris-lea/redis-server
    packages:
#      - redis-tools
#      - redis-server
services:
  - postgresql
#os:
#  - linux
